elastic/elasticsearch-k8s-metrics-adapter

pkg/client/elasticsearch/discovery.go
pkg/registry/registry.go

When processing the mapping result we should iterate through all the children nodes even if one of them is `*`

Mapping document parsing: fix metrics discovery

---

Dockerfile
Makefile
helm/templates/deployment.yaml
helm/values.yaml

This PR adds support for ARM64:
* Uses buildx to create and push images
* Allows toleration to be set to deploy on `kubernetes.io/arch=arm64`
This also drops UBI as the base image in favor of `gcr.io/distroless/static:nonroot`

Add support for ARM64

---

helm/templates/cluster-role-binding.yaml

Binding to cluster role `elasticsearch-metrics-apiserver-resource-reader` is missing.

Helm chart: add missing cluster role binding

---

pkg/client/elasticsearch/query.go

I was getting this error in my HPA (most likely because of a query which didn't return any values), though because the error doesn't display the actual value (whereas the `getTimestamp` one does), I was unable to know whether it was `nil`, or anything else.

Add value when getFloat has an incompatible one

---

.gitignore
Dockerfile
Makefile
go.mod
main.go
pkg/client/custom_api/client.go
pkg/client/elasticsearch/client.go
pkg/client/elasticsearch/discovery.go
pkg/client/elasticsearch/query.go
pkg/client/metrics_client.go
pkg/config/metric_types_test.go
pkg/monitoring/server.go
pkg/monitoring/server_test.go
pkg/provider/aggregation_provider.go
pkg/registry/clients.go
pkg/registry/fixtures.go
pkg/registry/registry.go
pkg/registry/registry_test.go
pkg/scheduler/job.go
pkg/scheduler/listeners.go
pkg/scheduler/scheduler.go

It appears this repository was renamed. But the package never was, which causes discrepancies between the folder in GOPATH and the actual package name.

Rename package to elasticsearch-k8s-metrics-adapter

---

.buildkite/pipeline.yml

This removes the global agent declaration to resolve an issue with the serverless-docker-builder where the image of the global agent is used with the agent definition used to build ARM images.

Remove global agent declaration

---

helm/templates/deployment.yaml
helm/values.yaml

This will remove the default cpu limit, as we currently do not want to adversely effect the performance of the metrics-adapter when nearing the cpu limits.
Verification of helm changes:
```
❯ helm template es-metrics . -s templates/deployment.yaml | yq '.spec.template.spec.containers[0].resources'
limits:
memory: 1Gi
requests:
cpu: "1"
memory: 1Gi
❯ helm template es-metrics . -s templates/deployment.yaml --set resources=null | yq '.spec.template.spec.containers[0]'
name: elasticsearch-metrics-apiserver
image: "docker.elastic.co/cloud-ci/k8s-arch/elasticsearch-k8s-metrics-adapter:latest"
workingDir: /
securityContext:
runAsNonRoot: true
runAsUser: 1111
envFrom:
- secretRef:
name: hpa-elasticsearch-credentials
env:
args: ["--secure-port", "6443", "--cert-dir=/var/run/serving-cert", "--v", …
```

Remove default cpu limit.

---

pkg/client/elasticsearch/discover_test.go
pkg/client/elasticsearch/discovery.go
pkg/client/elasticsearch/testdata/mapping.json

It looks like it's not possible to query root level metrics, moreover they appear in the metrics API prefixed by a dot like `pods/.metric`
That PR fix that
Before that change querying the metric server return either if querying with or without the `.`
```
Error from server (NotFound): the server could not find the metric .http_server_tcp_active for pods xxx with selector
Error from server: failed to get metrics backend: custom metric http_server_tcp_active is not served by any metric client
```
Thanks for the help on testing this @kvalliyurnatt I was able to deploy this in a dev env and able to query my root level metrics that were previously failing, non root level variable seems to still work well too
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta2/namespaces/xxxxxx/pods/xxx/h …
```

Fix root level metrics

---

catalog-info.yaml

This registers the service as a `Component` in Backstage, which is required to pass the PRR.
Relates to https://elasticco.atlassian.net/browse/PRR-3294.

Register the service as a Component in Backstage

---

helm/templates/_helpers.tpl
helm/templates/deployment.yaml

`podLabels` already existed in the helm chart, and I failed to include it in the labels included with the pods in the deployment in #55.

Fix Labels: Add back using `podLabels`.

---

helm/templates/deployment.yaml
helm/values.yaml
main.go
pkg/monitoring/server.go
pkg/profiling/server.go

This PR adds a seperate http server that can be used for profiling with pprof. This can be enabled using the helm chart.
The default port the server will run on is 8085. The profile can be collected by port-forwarding the specific port like 
```
kubectl port-forward pod/elasticsearch-metrics-apiserver-55556bb58d-9z6sj -n elastic-agent 8085
```
And then collecting data using pprof like below 
```
karthikeyanvalliyurnatt@Karthikeyans-MacBook-Pro  ~/workspace/kvalliyurnatt/elasticsearch-k8s-metrics-adapter   add-profiling ?  go tool pprof -png http://localhost:8085/debug/pprof/heap                                                           ✔  10501  14:40:38
Fetching profile over HTTP from http://localhost:8085/debug/pprof/heap
Saved profile in …
```

Add profiling server for pprof

---

README.md

The original url would return:
```
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "the server could not find the requested resource",
"reason": "NotFound",
"details": {},
"code": 404
}
```

Fix incorrect url in README.md

---

.buildkite/pipeline.yml
Dockerfile

- Update golang base image to build the binary to `v1.21.3`
- Update go-builder-buildkite-agent to `v1.21.3`
- Update golangci-lint to `v1.54.2`

Update to golang v1.21

---

Dockerfile
Makefile
main.go

Initialize service.version properly.
Update dockerfile to allow service.version.
Todo
```
{"log.level":"info","@timestamp":"2023-11-07T18:07:27.563Z","log.logger":"main","log.origin":{"function":"main.main","file.name":"elasticsearch-k8s-metrics-adapter/main.go","file.line":126},"message":"Starting elastic k8s metrics adapter...","service.type":"elasticsearch-k8s-metrics-adapter","service.version":"d33a44897b65","ecs.version":"1.6.0"}
```

Add ldflags to initialize service.version properly

---

.buildkite/pipeline.yml

[Update-image-tag](https://github.com/elastic/k8s-gitops-control-plane/blob/main/.buildkite/pipeline.update-image-tag.yml) is just a proxy of gpctl-promote-with-e2e-tests. Let's use the final pipeline directly.
The same implementation works on [object-storage-api](https://github.com/elastic/object-storage-api/blob/main/.buildkite/pipeline.yml#L87)
[Here is the pipeline for object-storage-api](https://buildkite.com/elastic/object-storage-api/builds/2891#018d16e9-743d-48f2-a15e-a65cb1078315), all the variables are in place.

[TLS-406] chore: replace update image tag with gpctl-promote-with-e2e-tests

---

.github/renovate.json

As noted in [0], the use of `branch` automerge is no longer possible due
to branch protection requirements, and although Renovate can handle the
failure by upgrading to use a PR, it adds noise for Infosec.
Instead, we can make sure we default to `pr` strategy.
[0]: https://groups.google.com/a/elastic.co/g/dev/c/3kGf9b7gfwE
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift) by Platform DevFlow</sub>

fix(renovate): don't use branch automerge

---

.buildkite/pipeline.yml

The SSH key file referenced in the drivah config that the previous version of serverless-docker-builder creates is being removed from CI agents, bump to the latest version to avoid breaking image builds.

bump serverless-docker-builder version

---

.github/renovate.json

Fixes #70 
My guess is that a public repo cannot rely on a private config preset.

Attempting to fix renovate config

---

.buildkite/pipeline.yml

Builds are failing with  
```
/usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
```
I have a hunch that it is lack of memory.

Increase memory for build all step

---

.buildkite/pipeline.elasticsearch-k8s-metrics-adapter-tests.yaml
.buildkite/pipeline.tests-production.yaml
.buildkite/pipeline.tests-qa.yaml
.buildkite/pipeline.tests-staging.yaml
helm/templates/_helpers.tpl
helm/templates/deployment.yaml
helm/values.yaml

- Enable the helm chart bits for progressive deployments
- Pass down deployment slice to QG

chore(progressive-deployment): enable for elasticsearch-k8s-metrics-adapter

---

.github/renovate.json

Group the dependencies in the renovate config so that we have lesser renovate PRs 
We will have three groups
1. Go dependencies
2. Elastic internal dependencies
3. Everything else
Additionally enable automerge for wolfi image updates

group renovate updates and enable automerge for wolfi image updates
